apiVersion: v1
kind: Service
metadata:
  labels:
    name: alertmanager-main
  name: alertmanager-main
spec:
  selector:
    app: simple-alertmanager
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093