apiVersion: v1
kind: Service
metadata:
  name: infra-fluentd
  labels:
    app: fluentd
spec:
  type: ClusterIP
  ports:
    - name: fluentd-monitor
      port: 24220
      targetPort: 24220
      protocol: TCP
    - name: fluentd-agent-tcp
      port: 24224
      targetPort: 24224
      protocol: TCP
    - name: fluentd-agent-udp
      port: 24224
      targetPort: 24224
      protocol: UDP
  
  selector:
    app: fluentd
