apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graph-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
